databases:
  - name: porfolioadmin
    databaseName: porfolioadmin
    user: rich

services:
  - type: web
    name: porfolioadmin
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: porfolioadmin
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false